name: Deploy Marp Slides to Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Compile presentation to Index HTML
        uses: KoharaKazuya/marp-cli-action@v4
        with:
          args: presentation.md -o index.html
          generate-html: false
          generate-pdf: false

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
